# Generated by Django 3.0.2 on 2020-01-07 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='body',
            old_name='question',
            new_name='post',
        ),
    ]
